Add Genomic Annotations Output
broadinstitute/adapt pull request #53
Opened 2021-06-29 21:21 UTC by priyappillai

Set up ADAPT to include genomic annotation information in it.
 
- [x] Add a command (`--write-annotation`) to allow people to write the annotations of the reference sequence to a file. 
- [ ] Add the overlapping annotations of a design to the output file

2021-07-20 17:48 UTC, haydenm requested changes
Awesome! 👍

2021-07-20 17:48 UTC, haydenm commented on bin/tests/test_design.py
> +        logging.disable(logging.WARNING)
And re-enable in the `tearDown()`.

2021-07-20 17:48 UTC, haydenm commented on bin/tests/test_design.py
> +        self.real_output_file = self.output_file.name + '.tsv'
I think it might be better to do this directly when making `self.output_file`. For example, will the "real" temporary file get deleted as it is now?

2021-07-20 17:48 UTC, haydenm commented on adapt/target_search.py
> +                headers.append('overlapping_annotations')
Probably should be `-` instead of `_` just for consistency

2021-07-20 17:48 UTC, haydenm commented on bin/design.py
> +        annotation_tsv = os.path.join(args.out_tsv_dir, label) if label \
If `label` is set, would this conflict with the output designs tsv?

2021-07-20 17:48 UTC, haydenm commented on bin/design.py
> +        annotation_tsv = os.path.join(args.out_tsv_dir, label) if label \
Never mind... it looks like it adds `.annotation.tsv`

2021-07-20 17:48 UTC, haydenm commented on bin/design.py
> +              "OUT_TSV.[cluster-number].tsv"))
This should be clear that OUT_TSV is the basename of the output file.

2021-07-20 17:48 UTC, haydenm commented on README.md
> -design.py sliding-window fasta FASTA_PATH -o probes.tsv -w 200 -gl 28 -gm 1 -gp 0.95
Also, it wasn't obvious to me that why this is the way to go in `fasta` mode. If it is the case, though, you should also update the `-o` help message in `design.py`.

2021-07-23 15:53 UTC, priyappillai commented on README.md
> -design.py sliding-window fasta FASTA_PATH -o probes.tsv -w 200 -gl 28 -gm 1 -gp 0.95
I took out the suffix because I wanted to make sure that the output file name would be consistent across input types; I think it's potentially confusing otherwise.

2021-08-02 16:47 UTC, priyappillai commented on adapt/prepare/align.py
> +    If indexes would go past the end of the sequence, '' is returned for
Switched to `None`; it was `''` to accommodate logic that has since been removed

2021-08-02 17:05 UTC, priyappillai commented on adapt/prepare/prepare_alignment.py
> +                            fw.write('\t'.join([annotation[header]
Not sure what you mean? Isn't that the case here?

2021-08-02 17:07 UTC, priyappillai commented on adapt/prepare/prepare_alignment.py
> +                            fw.write('\t'.join([annotation[header]
Did adjust so that the headers are defined here, rather than at the beginning of the function, if that's what you mean

2021-08-02 17:14 UTC, priyappillai commented on adapt/prepare/prepare_alignment.py
> +    annotations = []
Yes; modified to return `[]` instead of returning annotations if nothing is found in the loop!

2021-08-02 17:17 UTC, priyappillai commented on adapt/prepare/prepare_alignment.py
> +
Added some more detail to ref_accs in the docstring that hopefully makes it more clear that the annotations are based on a reference sequence but their positions have been modified to match the alignment.

2021-08-02 17:21 UTC, priyappillai commented on bin/tests/test_design.py
> +        logging.disable(logging.WARNING)
The teardown of the base class `TestDesignCase` includes enabling the logging.

2021-08-02 17:27 UTC, priyappillai commented on bin/tests/test_design.py
> +        self.real_output_file = self.output_file.name + '.tsv'
`self.output_file` is made in the base class, but `self.real_output_file` is slightly different if it's a `fasta` or an `auto-from-args`, which is why it's done in the subclasses. The "real" temporary file gets deleted because it's added to the list `self.files`, which deletes anything added to it. Will rename `self.files` to `self.files_to_delete` to make that more obvious!

2021-08-02 17:44 UTC, priyappillai commented on adapt/prepare/prepare_alignment.py
> +                for annotation in annotations:
Done in the docstring now!

2021-08-02 19:39 UTC, haydenm commented on README.md
> -design.py sliding-window fasta FASTA_PATH -o probes.tsv -w 200 -gl 28 -gm 1 -gp 0.95
I don't really agree about it being confusing but I think it's fine now that it's in the documentation.

2021-08-02 19:42 UTC, haydenm commented on adapt/prepare/prepare_alignment.py
> +                            fw.write('\t'.join([annotation[header]
Sory, I meant the names of the variables. `header` instead of `headers` and looping over something like `col_name` in `header` -- at least, I believe, that's how we name it elsewhere.

2021-08-02 19:44 UTC, haydenm commented on bin/tests/test_design.py
> +        self.real_output_file = self.output_file.name + '.tsv'
Got it, that helps!

2021-08-03 13:32 UTC, haydenm approved these changes

2021-08-03 17:06 UTC, merged