Restructure for Oligo Searcher Base Classes
broadinstitute/adapt pull request #57
Opened 2022-01-11 15:17 UTC by priyappillai

- Create base Searcher classes (`OligoSearcher`, `OligoSearcherMinimizeNumber`, `OligoSearcherMaximizeActivity`, and `GuideSearcher`) to make `GuideSearcherMinimizeGuides`, `GuideSearcherMaximizeActivity`, and `PrimerSearcherMinimizePrimers`. Simplify some of the code underlying these classes
- Change `guide_is_suitable_fn` (previously used for specificity check) to `is_suitable_fns` - a list of suitability functions-and make the `check_gc_content` a part of this list
- Rename `guide.py` in utils to `oligo.py` - adjust `design.py`, `alignment.py`, `coverage_analysis.py`, `alignment_query.py`, `target_search.py`, & `pick_test_targets.py` accordingly
- Move `construct_guide` from `alignment.py` to Guide/Primer searchers; rename to `construct_oligo`. Keep as unique for both as, while they are the same right now, I expect to change the Primer `construct_oligo` in the future
- Add sequence complementarity functions to `oligo.py`
- Make the default compression function return the input so that `compress` does not need to be an input to `compute_memoized`
- Change `blacklist` to `ignore`

2022-01-18 17:28 UTC, haydenm requested changes
Wow, this is a lot—well done! I think it changes my mind on the importance of test coverage. Since there is so much going on that is getting difficult to check through carefully, and we do have great unit tests, it would be very helpful to know what (if any) parts we are missing in tests.

2022-01-18 17:28 UTC, haydenm commented on adapt/utils/oligo.py
> +def is_complement(oligo_a, oligo_b):
Can you clarify the description comment? I _think_ I know what it does after reading the code, but could not tell from the comment. It's not actually expanding out all the possible instances of an ambiguous `oligo_a`, and comparing those with `oligo_b` (which is how the comment seems to read). Are you sure, algorithmically, that this will return the same solution as if you were to do that?

2022-01-18 17:28 UTC, haydenm commented on adapt/utils/oligo.py
> +def is_symmetric(oligo):
What is this for? (Hairpinning? But my guess is that there are other available functions to check that.) Like the above, the comment is unclear to me. An example may help.

2022-01-18 17:28 UTC, haydenm commented on adapt/utils/search.py
> +"""Methods for searching for optimal guides to use for a diagnostic.
This is a lot… besides renamings, is there anything substantially different from what was previously in `guide_search` that I should look at?

2022-01-18 17:28 UTC, haydenm commented on bin/design.py
> +                    do_not_memoize=args.do_not_memoize_guide_computations)
Does the `do_not_memoize` argument now also apply to primers (given the rename)? If so, should the command-line argument `--do-not-memoize-guide-computations` also be renamed?

2022-01-18 17:28 UTC, haydenm commented on bin/design.py
> +        help=("Path to a FASTA file that gives k-mers to ignored from "
"ignore" (I realize there was also an original typo with "blacklisted").

2022-01-18 17:28 UTC, haydenm commented on bin/design.py
> +        help=("Path to a FASTA file that gives k-mers to ignored from "
I'm also wondering if you had a good reason for "ignore" as opposed to "disallowed" or "blocklist"? To me, the latter choices seem more direct about not allowing designs with those k-mers.

2022-01-19 16:34 UTC, priyappillai commented on adapt/guide_search.py
> -            missing_data_params, algorithm='random-greedy', **kwargs):
It's an issue of multiple inheritance. The parameters that are explicitly mentioned here (`guide_length`, `soft_guide_constraint`, `hard_guide_constraint`, and `penalty_strength`) all are required arguments of the superclasses of GuideSearcherMaximizeActivity. If they were instead in `kwargs`, Python wouldn't search through them for the required arguments to the superclass constructors and would raise an error that required arguments aren't included.

2022-01-19 16:39 UTC, priyappillai commented on adapt/primer_search.py
> +class PrimerSearcherMinimizePrimers(search.OligoSearcherMinimizeNumber):
Because there's only one primer searcher (as of now), and there were multiple GuideSearchers. Generally, I made superclasses for any repeated code between multiple classes. I separated the GuideSearcher into its own class in case there were any other guide specific methods/arguments that needed to be added to both searchers. I could make a PrimerSearcher superclass, but that may make more sense to do when I add a new PrimerSearcher subclass.

2022-01-19 19:18 UTC, priyappillai commented on adapt/utils/oligo.py
> +def is_symmetric(oligo):
Symmetry specifically changes the melting temperature/delta G, which is why it's here. The situation it accounts for is if you have something like this:
`3'-GCATATGC-5'`
`5'-CGTATACG-5'`
it would completely bind to itself, therefore changing the delta G calculations.
It would come up in self dimer calculations and would almost certainly be cancelled out there; while my current (unpushed) code for thermodynamics just uses this for delta G, it could/should be made into a quick early filter.
Will add the example above to the comments!

2022-01-21 18:00 UTC, priyappillai commented on adapt/utils/oligo.py
> +def is_complement(oligo_a, oligo_b):
The algorithm is based on [how ambiguous base pairs work for primers](https://www.idtdna.com/pages/products/custom-dna-rna/mixed-bases), which is that an equal percentage of each possible based is randomly produced in the final set of sequences (ex. `WVN` would have 50% `A` / 50% `T` at the first position, 33% `A` / 33% `C` / 33% `G` in the second, and 25% `A` / 25% `C` / 25% `G` / 25% `T` in the third). Based on that, the percentage of sequences that are complementary would be the percent that complement on the first position times the percent that complement at the second and so on. It does list out all the possibilities at the base level in the for loops, but just uses the fraction of each base that complements multiplied together for the overall fraction. Doing it this way is significantly more efficient than checking every option (unless perhaps you did a dynamic programming version? Still think this is likely more efficient/simple). 
Since it's more of an implementation detail, I think adding more comments throughout the function might also help? I can add something brief to the function description about it, then go into more detail in the code itself.

2022-02-03 09:23 UTC, priyappillai commented on adapt/guide_search.py
> +            num_needed: dict mapping universe group ID to the number of sequences
More that the groups are ignored even if they exist (coverage is determined based on the total number of sequences covered). Adding that in!

2022-02-03 09:25 UTC, priyappillai commented on adapt/primer_search.py
> +    def construct_oligo(self, start, oligo_length, seqs_to_consider,
We had discussed that the primer construct_oligo may change with PCR functionality, but I think it makes sense to leave this as a default function in search.py and override for PCR if needed. Changing now!

2022-02-07 15:32 UTC, haydenm commented on adapt/guide_search.py
> -            missing_data_params, algorithm='random-greedy', **kwargs):
I think I understand — in other words, they don't have defaults in the superclass?

2022-02-07 15:33 UTC, haydenm commented on adapt/primer_search.py
> +class PrimerSearcherMinimizePrimers(search.OligoSearcherMinimizeNumber):
Ok, that makes sense.

2022-02-07 15:40 UTC, haydenm commented on adapt/utils/oligo.py
> +def is_complement(oligo_a, oligo_b):
How you just described it here makes a lot of sense, and now the function does too—way more than it did on my first read. Yes, I think you should add something to the function description as well as comments throughout the function.

2022-02-07 15:43 UTC, haydenm commented on adapt/utils/oligo.py
> +def is_symmetric(oligo):
That makes more sense so, like with `is_complement`, it would be good to expand in the comment. Also, is `is_palindromic` not a more precise name? ([https://en.wikipedia.org/wiki/Palindromic_sequence](https://en.wikipedia.org/wiki/Palindromic_sequence))

2022-02-07 15:49 UTC, haydenm approved these changes
The changes look good! Just a few helpful comment additions would help.

2022-02-07 20:53 UTC, haydenm commented on adapt/utils/search.py
> +                    self.max_oligo_length+1, self.aln.seq_length)):
This is really an edge case, but there might also need to be a +1 for `self.aln.seq_length`.

2022-02-07 20:54 UTC, haydenm commented on adapt/utils/search.py
> +            p_best = (None, None, 0)
I think this is probably ok because the output of `construct_oligo()` is a marginal contribution and should always be nonzero — but I'm not certain. To be safe, maybe this could be -infinity rather than 0.

2022-02-07 20:56 UTC, haydenm commented on adapt/utils/search.py
> +                short_olg_seq = olg_seq[:oligo_length]
I'm confused by what is happening here. Is it just trying out shorter oligos extracted from one end because `ground_set` was determined from the max oligo length? If so, this seems important so it should be spelled out in comments.

2022-02-07 20:57 UTC, haydenm commented on adapt/utils/search.py
> +            for oligo_length in range(self.min_oligo_length, len(olg_seq)+1):
I don't think the +1 is needed here because `oligo_length` will still reach `len(olg_seq)` without it.

2022-02-17 18:12 UTC, priyappillai commented on adapt/utils/search.py
> +            p_best = (None, None, 0)
Arguably, this is what makes sure the marginal contribution is positive? If the marginal contribution of the best oligo is negative, it'll return None, which seems reasonable

2022-02-17 18:16 UTC, priyappillai commented on adapt/utils/search.py
> +                short_olg_seq = olg_seq[:oligo_length]
Yup! Will add comments

2022-02-17 18:25 UTC, priyappillai commented on adapt/utils/search.py
> +            for oligo_length in range(self.min_oligo_length, len(olg_seq)+1):
It is necessary, due to the end of the range being exclusive AND the end of the subsequence in the next line (`[:oligo_length]`) being exclusive. Can add that as a comment!

2022-02-21 18:35 UTC, haydenm approved these changes

2022-02-21 18:35 UTC, haydenm commented on adapt/utils/search.py
> +            p_best = (None, None, 0)
Ok, I think that's a reasonable way to look at it. I was thinking that it should set `p_best` even if the marginal contribution is negative, but it's probably better to think that it shouldn't.

2022-02-23 14:14 UTC, merged