Add sequence weighting
broadinstitute/adapt pull request #63
Opened 2022-04-13 18:17 UTC by priyappillai

Allow users to manually set their own weights per sequence for FASTA input or to automatically determine weights depending on the log of the number of sequences in a grouping

adapt/utils/weight.py
- Create file
- Add normalize
- Add weighted percentile
- TODO: should have unit tests

adapt/utils/seq_io.py
- Add read_sequence_weights

adapt/alignment.py
- Add normalized weights as a property of Alignment objects
- Add seq_idxs_weighted function to get the sum of the weights of a subset of sequences
- In construct_guide, change num_needed to percent_needed
- In determine_consensus_sequence/position_entropy/base_percentages, use weights to calculate base percentages rather than counts
- In determine_most_common_sequences, use weights for sequence percentages rather than counts

adapt/tests/test_alignment.py
- Add tests for seq_idx_weighted
- Add tests for weighted construct_guide/determine_consensus_sequence/position_entropy/base_percentages/determine_most_common_sequences

adapt/guide_search.py
- In guide_set_activities_percentile, use weighted percentile
- In guide_set_activities_expected_value/guide_set_activities_expected_value_per_guide/guide_activities_expected_value/obj_value/_ground_set_with_activities_memoized/_analyze_guides/_analyze_guides_memoized/add_guide, use weighted average
- In _construct_guide_memoized/_find_optimal_guide/_find_guides_in_window/add_guide_to_cover/score_collection_of_guides, use percent_needed rather than num_needed
- In total_frac_bound_by_guides, use weighted total (using seq_idxs_weighted)

adapt/tests/test_guide_search.py
- Modify tests to use percent needed rather than num needed
- Use almost equal for percent needed for floating points issues

bin/design.py
- Change prepare alignments to use 0 for the 'tax ID' and the unaligned FASTA file name for the 'segment'
- Set up preparation steps to also include outputting weights

bin/tests/test_design.py
- Add weighted argument type
- Test weighted FASTA input

2022-04-25 20:47 UTC, haydenm requested changes
This is super impressive work @priyappillai, in everything from the tricky software implementations (e.g., NCBI parsing) through more complicated functions (e.g., weighted percentiles). And it will definitely play, I think, a key role in the short/medium term in how we go about correcting for sampling biases during design.

2022-04-25 20:47 UTC, haydenm commented on adapt/utils/seq_io.py
> +    weights = defaultdict(lambda: 1)
Not sure, but I think a downside of returning a `defaultdict()` might be that if a sequence is not given a weight in the input, it will automatically be considered to have (unnormalized) weight of 1?

2022-04-25 20:47 UTC, haydenm commented on bin/design.py
> +              "given a default weight of 1."))
This addresses my question in an earlier comment in `seq_io.py`. Why is it the right option, since 1 can mean anything based on the magnitudes of the weights?

2022-04-25 20:47 UTC, haydenm commented on bin/design.py
> -    # Set NCBI API key
Why the deletion?

2022-04-25 20:47 UTC, haydenm commented on bin/design.py
> -    # Set NCBI API key
Nevermind, I see now that I think it's because you merged two blocks of code.

2022-04-25 20:47 UTC, haydenm commented on bin/design.py
> +    input_auto_common_subparser.add_argument('--weight-by-log-size-of-subtaxa',
May want to check somewhere that this and `--weight-sequences` are not both set (it seems, if they are, that the log size of subtext will override the file?).

2022-04-25 20:47 UTC, haydenm commented on adapt/utils/weight.py
> +    """Weight sequences by the log of the number of sequences in the group
This header should be more descriptive, i.e., every sequence falls into exactly one group (maybe check/assert this?), a group's weight is proportional to the log of its size, and every sequence in the group gets that group's weight divided by the size of the group.

2022-04-25 20:47 UTC, haydenm commented on adapt/utils/weight.py
> +        # Since sequence weights are normalized, the sum of weights of
Check that they are indeed normalized and/or include that in the description of `seq_norm_weights`.

2022-04-25 20:47 UTC, haydenm commented on adapt/utils/weight.py
> +    """Take a weighted percentile of activities, using 'lower' interpolation
I think this should either explain a bit more what we mean by weighted percentile or link to something that does, e.g., [https://en.wikipedia.org/wiki/Percentile#The_weighted_percentile_method](https://en.wikipedia.org/wiki/Percentile#The_weighted_percentile_method)

2022-04-25 20:47 UTC, haydenm commented on adapt/utils/tests/test_weight.py
> +    def test_percentile(self):
This is such a complicated function! I'm going to ask for many more test examples :)  Both standard uses and edge cases.

2022-04-26 12:44 UTC, priyappillai commented on adapt/guide_search.py
> +                weights=np.array(self.aln.seq_norm_weights)[best_guide])
It's switched to a numpy array here in order to use `best_guide` as a mask; L399 doesn't need a mask

2022-04-26 12:52 UTC, priyappillai commented on adapt/alignment.py
>          """Compute fraction of sequences with missing data at each position.
I'm not sure entirely what you mean? It's just making sure that the weights of the original alignment are still reflected in the alignment of the smaller range. With the exception of `pick_test_targets` (which will use an alignment without weights anyway), it is exclusively used for getting alignments for guides, which should use the weights.

2022-04-26 12:57 UTC, priyappillai commented on adapt/prepare/prepare_alignment.py
> +            sequence_weights.append(defaultdict(lambda: 1))
This is unnormalized even with `weight_by_log_group`; it will eventually be normalized when put in the alignment.

2022-04-27 13:13 UTC, priyappillai commented on bin/design.py
> +              "given a default weight of 1."))
I think the other options would be to have it fail if there isn't a weight listed for every sequence or to set the weight of that sequence to 0. 
I don't like having it fail mostly because I can imagine that being fairly annoying if you only want to weigh a subset of sequences.
For 0 as a default, I was avoiding allowing any weights to be 0 (since you could just remove that sequence from the FASTA in that case), but I can imagine scenarios where it's useful (such as making designs for various subsets of a FASTA).
I originally picked 1 as the default because I figured it would be easiest conceptually to scale other sequences against a default of 1. 
I'm not certain whether 0 or 1 makes more sense as a default; what do you think?

2022-04-27 17:32 UTC, haydenm commented on bin/design.py
> +              "given a default weight of 1."))
I was thinking to fail if a sequence is missing from the input file, but your comment about wanting to only weigh a subset of sequences makes sense and is totally reasonable. Definitely don't think 0 is the way to go. Maybe as a compromise stick with 1, but have a log message (at `WARNING` level) if ≥1 sequence is missing from the file, just to remind the user that they will be given a weight of 1?

2022-04-27 17:34 UTC, priyappillai commented on adapt/prepare/prepare_alignment.py
> +            sequence_weights.append(defaultdict(lambda: 1))
Yup, L131 in design.py to be precise!

2022-04-29 18:33 UTC, priyappillai commented on adapt/alignment.py
>          """Compute fraction of sequences with missing data at each position.
Looking at what this is doing, I don't actually think it should be weighted at all (especially given how it's memoized).  I might switch this back to being unweighted?

2022-05-02 17:35 UTC, priyappillai commented on adapt/prepare/ncbi_neighbors.py
> +def get_rank(taxid, rank):
Yeah, I overlapped the naming of terms here. Can rename to `get_taxonomy_name_of_rank`?

2022-05-02 17:37 UTC, priyappillai commented on adapt/utils/seq_io.py
> +    weights = defaultdict(lambda: 1)
(Discussed in the subsequent comment)

2022-05-03 17:19 UTC, priyappillai commented on bin/design.py
> +    input_auto_common_subparser.add_argument('--weight-by-log-size-of-subtaxa',
`--weight-sequences` is only in the FASTA subparser, so they shouldn't be allowed to both be set

2022-05-04 12:52 UTC, priyappillai commented on adapt/utils/weight.py
> +        # Since sequence weights are normalized, the sum of weights of
Ended up checking if they were normalized, and normalizing them if they were not!

2022-05-05 17:30 UTC, haydenm commented on adapt/alignment.py
>          """Compute fraction of sequences with missing data at each position.
Yeah, if it's not used for anything where weighted is needed, then unweighted makes more sense.

2022-05-05 18:03 UTC, haydenm approved these changes
👍  Changes look good, and I just made some minor updates to the README.

2022-05-06 14:46 UTC, merged