Add a thermodynamic primer mode to design.py
broadinstitute/adapt pull request #67
Opened 2022-06-28 09:04 UTC by priyappillai

Create ThermoPredictor and use it to design PCR primers with `design.py`

2022-06-28 19:12 UTC, haydenm requested changes
Exciting to see this!! Other than my line-by-line comments, my main requests are:
- A more descriptive PR summary saying what each component does
- A mention (ideally, description) in the README as well as at least one example

2022-06-28 22:01 UTC, priyappillai commented on adapt/utils/search.py
> +            self.predictor.min_activity)
although I do need to update the comment above this line...

2022-06-28 22:03 UTC, priyappillai commented on adapt/utils/search.py
> +        self.required_oligos = required_oligos if required_oligos is not None else {}
They were defaulted to dicts previously actually! They do make more sense as sets though, so will update.

2022-06-28 22:04 UTC, priyappillai commented on adapt/utils/predict_activity.py
> +        self.min_activity = 0
(resolved below)

2022-06-28 22:05 UTC, priyappillai commented on adapt/utils/predict_activity.py
> +        self.min_activity = 0
Actually, should check whether I should set it to `regression_lower_bound`.

2022-06-28 22:05 UTC, priyappillai commented on adapt/utils/predict_activity.py
> +        self.min_activity = 0
(resolved below)

2022-06-28 22:06 UTC, priyappillai commented on adapt/target_search.py
> +        # If the primer searcher uses the 'max' objective, this is using a
I was considering it, but was trying to avoid the extra argument. I do think it's helpful for other objectives especially though!

2022-06-28 22:08 UTC, priyappillai commented on adapt/target_search.py
> +                cost_primers *= -1
This is because the logic below refers to the objective type for the guide searcher and implicitly assumes the primer searcher has a minimization objective. I can add comments for this!

2022-06-28 22:12 UTC, priyappillai commented on adapt/target_search.py
> +            obj_value_shift=None, mutator=None, primer_set_filters=None):
Pre/post refers to before/after the individual primer's activity score is calculated. Primer set filters is a set of filters used when checking if multiple primers can work together in an assay, after determining their activity. Can add more detail on that in the documentation, but it should probably still use `_fns` since it is similar to `pre`/`post_filter_fns`

2022-06-28 22:15 UTC, priyappillai commented on adapt/target_search.py
> +        for i in range(len(left_primers) - 1):
I think my logic had originally been that there must be at least one primer to the right of it, so it can't be the last primer, but that isn't necessarily true if the right primer list is a different list than the left primer list. Will fix that.

2022-06-29 13:53 UTC, priyappillai commented on adapt/target_search.py
> +        assert self.gs.obj_type in ['min', 'max']
It's currently being used for the shift, but I think that can use `gs.obj_type`. The shift might require more adjustments.

2022-06-29 13:56 UTC, priyappillai commented on adapt/target_search.py
> +            right_primers = left_primers
The original version of this used only one list for both primers, so I figured this was fine (and I'm fairly certain that this list does not get edited)

2022-06-29 13:59 UTC, priyappillai commented on adapt/primer_search.py
> +                frac_bound = self.total_frac_bound(start, end, primers_in_cover)
This is a bit of a quirk of the fact that `min` refers to min number and `max` refers to max activity. I do need to check this over though, because I am now realizing that the max activity searcher might allow multiple positions for the oligo set it generates, whereas min number does not, and that would have an effect on how amplicon length is handled/calculated (generally, primers should be all in the same location).

2022-06-29 15:13 UTC, priyappillai commented on adapt/primer_search.py
> +            obj_value: value to use to compare primer covers to each other
'primer covers' refers to a primer set with sufficient coverage, so I believe this is accurate? (where coverage level is average melting temperature difference from the ideal on sequences)

2022-06-30 15:19 UTC, haydenm commented on adapt/primer_search.py
> +            obj_value: value to use to compare primer covers to each other
Re: our discussion, "primer set" works and avoids "cover"

2022-06-30 15:30 UTC, haydenm commented on adapt/target_search.py
> +                cost_primers *= -1
Ok, I think the logic is ok but needs to be way more clear in one or more places that:

- the overall objective is based on `self.gs.obj_type` (GuideSearcher), and that's why you need the negation in L280
- cost for primers is not really a cost when maximizing

2022-06-30 17:59 UTC, priyappillai commented on adapt/primer_search.py
> +                frac_bound = self.total_frac_bound(start, end, primers_in_cover)
The length variation searches by window size of the maximum oligo length. In theory, that means multiple primers of different length and different locations within that window could be chosen. While not technically accurate, the difference between this method and providing a more precise amplicon length (as this uses the worst case amplicon length)

2022-06-30 18:13 UTC, haydenm commented on adapt/primer_search.py
> +                frac_bound = self.total_frac_bound(start, end, primers_in_cover)
I think this is ok, even if it wasn't what was initially intended! It's normal to have primers of slightly different lengths or even different positions

2022-06-30 20:04 UTC, priyappillai commented on adapt/target_search.py
> +        # If the primer searcher uses the 'max' objective, this is using a
Actually, the PrimerSearcher object doesn't really define whether the model uses Tm, but rather the predictor. I'm using `isinstance(self.lps.predictor, predict_activity.TmPredictor)` instead here?

2022-06-30 21:31 UTC, haydenm approved these changes

2022-07-01 03:00 UTC, merged